import { Injectable } from '@angular/core';
import { InputName } from '../interface';

/**
 * @class ConfigForm
 * @readonly Configuração dos atributos de formulários
 */
@Injectable({ providedIn: 'root' })
export class ConfigForm {
  public readonly input: InputName = {
    id: null,
    firstName: {
      name: 'firstName',
      label: 'Nome',
      placeholder: 'Entre com seu nome',
      type: 'text',
      actionLabel: 'Entre com seu nome',
      readonly: false,
      msg: {
        invalid: 'Digite nome próprio ou todas letras em maiuscúlo.',
        empty: 'obrigatório!',
        min: null,
        max: null,
      },
    },
    name: {
      name: 'name',
      label: 'Nome',
      placeholder: 'Entre com seu nome',
      type: 'text',
      actionLabel: 'Entre com seu nome',
      readonly: false,
      msg: {
        invalid: 'Digite nome próprio ou todas letras em maiuscúlo.',
        empty: 'obrigatório!',
        min: null,
        max: null,
      },
    },
    title: {
      name: 'title',
      label: 'Titulo',
      placeholder: 'Entre com titulo',
      type: 'text',
      actionLabel: 'Entre com titulo',
      readonly: false,
      msg: {
        invalid: 'Digite nome próprio ou todas letras em maiuscúlo.',
        empty: 'obrigatório!',
        min: null,
        max: null,
      },
    },
    district: {
      name: 'district',
      label: 'Bairro',
      placeholder: 'Digite o bairro',
      type: 'text',
      actionLabel: 'Digite o bairro',
      readonly: false,
      msg: {
        invalid: 'Digite nome próprio ou todas letras em maiuscúlo.',
        empty: 'obrigatório!',
        min: null,
        max: null,
      },
    },
    street: {
      name: 'street',
      label: 'Rua',
      placeholder: 'Digite a rua',
      type: 'text',
      actionLabel: 'Digite a rua',
      readonly: false,
      msg: {
        invalid: null,
        empty: 'obrigatório!',
        min: null,
        max: null,
      },
    },
    // eslint-disable-next-line @typescript-eslint/naming-convention
    zip_code: {
      name: 'zip_code',
      label: 'CEP',
      placeholder: 'Digite o cep',
      type: 'text',
      actionLabel: 'Digite o cep',
      readonly: false,
      msg: {
        invalid: null,
        empty: 'obrigatório!',
        min: null,
        max: null,
      },
    },
    numberr: {
      name: 'numberr',
      label: 'Número',
      placeholder: 'Digite o numero',
      type: 'text',
      actionLabel: 'Digite o numero',
      readonly: false,
      msg: {
        invalid: null,
        empty: 'obrigatório!',
        min: null,
        max: null,
      },
    },
    block: {
      name: 'block',
      label: 'Quadra',
      placeholder: 'Digite a quadra',
      type: 'text',
      actionLabel: 'Digite a quadra',
      readonly: false,
      msg: {
        invalid: null,
        empty: 'obrigatório!',
        min: null,
        max: null,
      },
    },
    allotment: {
      name: 'allotment',
      label: 'Lote',
      placeholder: 'Digite o lote',
      type: 'text',
      actionLabel: 'Digite o lote',
      readonly: false,
      msg: {
        invalid: null,
        empty: 'obrigatório!',
        min: null,
        max: null,
      },
    },
    complement: {
      name: 'complement',
      label: 'Complemento',
      placeholder: 'Ex: Casa 4 / Bloco A3, Apartamento 204',
      type: 'text',
      actionLabel: 'Complemento',
      readonly: false,
      msg: {
        invalid: null,
        empty: 'obrigatório!',
        min: null,
        max: null,
      },
    },
    city: {
      name: 'city',
      label: 'Cidade',
      placeholder: 'Digite a cidade',
      type: 'text',
      actionLabel: 'Digite a cidade',
      readonly: false,
      msg: {
        invalid: null,
        empty: 'obrigatório!',
        min: null,
        max: null,
      },
    },
    uf: {
      name: 'uf',
      label: 'Estado',
      placeholder: 'Digite o estado',
      type: 'text',
      actionLabel: 'Digite o estado',
      readonly: true,
      msg: {
        invalid: null,
        empty: 'obrigatório!',
        min: null,
        max: null,
      },
    },
    description: {
      name: 'description',
      label: 'Descrição',
      placeholder: 'Entre com uma descrição',
      type: 'text',
      actionLabel: 'Entre com uma descrição',
      readonly: false,
      msg: {
        invalid: null,
        empty: 'obrigatório!',
        min: null,
        max: null,
      },
    },
    blockade: {
      name: 'blockade',
      label: 'Bloquear',
      placeholder: 'Bloquear usuário',
      type: 'radio',
      actionLabel: 'Bloquear usuário',
      readonly: false,
      msg: {
        invalid: null,
        empty: 'obrigatório!',
        min: null,
        max: null,
      },
    },
    mobilePhone: {
      name: 'mobilePhone',
      label: 'Telefone celular',
      placeholder: 'Digite o celular',
      type: 'tel',
      actionLabel: 'Digite o celular',
      readonly: false,
      msg: {
        empty: 'obrigatório!',
        min: 'Mínimo de 15 digitos.',
        max: 'Máximo de 15 digitos.',
      },
    },
    phone: {
      name: 'phone',
      label: 'Telefone fixo',
      placeholder: 'Digite o telefone fixo',
      type: 'tel',
      actionLabel: 'Digite o telefone fixo',
      readonly: false,
      msg: {
        empty: 'obrigatório!',
        min: 'Mínimo de 13 digitos.',
        max: 'Máximo de 13 digitos.',
      },
    },
    whatsapp: {
      name: 'whatsapp',
      label: 'Whatsapp',
      placeholder: 'Digite whatsapp',
      type: 'tel',
      actionLabel: 'Digite whatsapp',
      readonly: false,
      msg: {
        empty: 'obrigatório!',
        min: 'Mínimo de 15 digitos.',
        max: 'Máximo de 15 digitos.',
      },
    },
    facebook: {
      name: 'facebook',
      label: 'Facebook',
      placeholder: 'https://www.facebook.com/******.*****.9876543',
      type: 'text',
      actionLabel: 'Digite o endereço do facebook',
      readonly: false,
      msg: {
        invalid: 'Endereço não está incorreto.',
        empty: 'obrigatório!',
      },
    },
    instagran: {
      name: 'instagran',
      label: 'Instagran',
      placeholder: 'https://www.instagram.com/',
      type: 'text',
      actionLabel: 'Digite o endereço do instagran',
      readonly: false,
      msg: {
        invalid: 'Endereço não está incorreto.',
        empty: 'obrigatório!',
      },
    },
    lastName: {
      name: 'lastName',
      label: 'Sobrenome',
      placeholder: 'Entre com seu sobrenome',
      type: 'text',
      actionLabel: 'Entre com seu sobrenome',
      readonly: false,
      msg: {
        invalid: 'Digite nome próprio ou todas letras em maiuscúlo.',
        empty: 'obrigatório!',
        min: null,
        max: null,
      },
    },
    email: {
      name: 'email',
      label: 'Email',
      placeholder: 'Entre com seu email',
      type: 'email',
      actionLabel: 'Entre com seu email',
      readonly: false,
      msg: {
        invalid: 'inválido!',
        empty: 'obrigatório!',
        min: null,
        max: null,
      },
    },
    level: {
      name: 'level',
      label: 'Nível',
      placeholder: 'Entre com seu nível',
      type: 'radio',
      actionLabel: '',
      readonly: false,
      msg: {
        invalid: 'inválido!',
        empty: 'obrigatório!',
        min: null,
        max: null,
      },
    },
    type: {
      name: 'type',
      label: 'Plano',
      placeholder: 'Selecione um plano',
      type: 'radio',
      actionLabel: '',
      readonly: false,
      msg: {
        invalid: 'inválido!',
        empty: 'obrigatório!',
        min: null,
        max: null,
      },
    },
    response: {
      name: 'response',
      label: 'Deseja uma resposta?',
      placeholder: 'Deseja uma resposta?',
      type: 'checkbox',
      actionLabel: '',
      readonly: false,
      msg: {
        invalid: 'inválido!',
        empty: 'obrigatório!',
        min: null,
        max: null,
      },
    },

    period: {
      name: 'period',
      label: 'Período',
      placeholder: 'Selecione um período',
      type: undefined,
      actionLabel: '',
      readonly: false,
      msg: {
        invalid: 'inválido!',
        empty: 'obrigatório!',
        min: null,
        max: null,
      },
    },
    passwordCurrent: {
      name: 'passwordCurrent',
      label: 'Senha atual',
      placeholder: 'Entre com sua senha atual',
      type: 'password',
      actionLabel: 'Entre com sua senha atual',
      readonly: false,
      msg: {
        invalid: '',
        empty: 'obrigatório!',
        min: '',
        max: '',
      },
    },
    password: {
      name: 'password',
      label: 'Senha',
      placeholder: 'Entre com sua senha',
      type: 'password',
      actionLabel: 'Entre com sua senha',
      readonly: false,
      msg: {
        invalid: 'inválida!',
        empty: 'obrigatório!',
        min: 'mínimo 8.',
        max: 'maxímo 20.',
      },
    },
    passwordConfirmation: {
      name: 'passwordConfirmation',
      label: 'Confirmar senha',
      placeholder: 'Repita sua senha',
      type: 'password',
      actionLabel: 'Repita sua senha',
      readonly: false,
      msg: {
        invalid: 'senha inválida!',
        empty: 'obrigatório!',
        min: 'mínimo 8.',
        max: 'maxímo 20.',
        mustMatch: 'incorreto.',
      },
    },
    stayConnected: {
      name: 'stayConnected',
      label: 'Permanecer conectado?',
      placeholder: 'Permanecer conectado?',
      type: 'checkbox',
      actionLabel: null,
      readonly: false,
      msg: {
        invalid: null,
        empty: null,
        min: null,
        max: null,
      },
    },
    terms: {
      name: 'terms',
      label: 'Aceitar termos!',
      placeholder: '',
      type: 'checkbox',
      actionLabel: 'Aceitar termos de uso!',
      readonly: false,
      msg: {
        invalid: 'Você precisa aceitar os termos de uso!',
        empty: 'Termos obrigatório!',
        min: '',
        max: '',
      },
    },
    _csrf: null,
  };
}
